- name: "MOTD | Set Login Prompt"
  copy:
    content: "{{ banners.login }}\n"
    dest: "/etc/issue"
    owner: root
    group: root
    mode: '0644'
- name: "Finalize | Reset MOTD"
  file:
    state: "{{ item }}"
    path: "/etc/update-motd.d/"
    owner: root
    group: root
    mode: '0755'
  loop:
    - absent
    - directory
- name: "Finalize | Remove MOTD News config"
  file:
    state: "absent"
    path: "/etc/default/motd-news"
- name: "MOTD | Set MOTD"
  copy:
    content: "{{ banners.motd }}"
    dest: "/etc/update-motd.d/00-motd"
    owner: root
    group: root
    mode: '0755'
