- name: "Cloud-Init | configure network renderer"
  copy:
    content: |
      # prefer to render via netplan instead of /etc/network/interfaces even if ifupdown is present
      system_info:
        network:
          renderers: ['netplan', 'eni', 'sysconfig']
    dest: "/etc/cloud/cloud.cfg.d/90_override_renderer.cfg"
- name: "Cloud-Init | Mask ssh.socket allowing cloud-init to configure without failures"
  systemd:
    masked: yes
    name: ssh.socket

- name: "Cloud-Init | Ensuring cloud-init overrides directory exists"
  file:
    path: "/etc/systemd/system/cloud-init-local.service.d"
    state: directory
    mode: '0755'
- name: "Cloud-Init | Place cloud-init override file"
  template:
    src: cloud-init-local-overrides.j2
    dest: "/etc/systemd/system/cloud-init-local.service.d/override.conf"
    mode: '0644'
