- name: "Finalize | Removing .pyc files"
  shell:
    cmd: |
        find "/usr/" "/var/" \( -name "*.pyc" -o -name "__pycache__" \) -delete
        apt -y clean

- name: "Finalize | Ensure no /etc/machine-id is delivered in image"
  file:
    path: /etc/machine-id
    state: absent

- name: "Finalize | remove /var/lib/dbus/machine-id"
  file:
    path: /var/lib/dbus/machine-id
    state: absent

- name: "Finalize | symlink /var/lib/dbus/machine-id to /etc/machine-id"
  file:
    src: /etc/machine-id
    dest: /var/lib/dbus/machine-id
    owner: root
    group: root
    state: link
    force: yes
