- name: "Kubernetes | Ensuring systemd preset directory exists"
  file:
    path: "/etc/systemd/system-preset"
    state: directory
    mode: '0755'
# Started instead by cloud-init run commands
- name: "Kubernetes | Dont enable kubelet unit by default"
  copy:
    content: 'disable kubelet.service'
    dest: /etc/systemd/system-preset/00-kubelet.preset
