- name: "Including any user-defined vars"
  include_vars:
    file: main.yaml
    name: user-vars

- block:
  - name: "write user-provided files"
    include_tasks: write-user-files.yaml
  - name: "configure cloud-init"
    include_tasks: cloud-init.yaml
  - name: "configure modules"
    include_tasks: modules.yaml
  - name: "configure limits"
    include_tasks: limits.yaml
  - name: "configure sysctl"
    include_tasks: sysctl.yaml
  - name: "configure grub"
    include_tasks: grub.yaml
  - name: "configure kubernetes"
    include_tasks: kubernetes.yaml
  - name: "configure locale"
    include_tasks: locale.yaml
  - name: "configure hostname and hosts"
    include_tasks: hostname-hosts.yaml
  - name: "configure banners"
    include_tasks: banners.yaml
  - name: "unattended upgrades"
    include_tasks: unattended-upgrades.yaml
  - name: "configure base systemd"
    include_tasks: systemd.yaml
  - name: "configure user-defined systemd"
    include_tasks: systemd-user.yaml
  - name: "configure file permissions"
    include_tasks: file-permissions.yaml
  - name: "finalise rootfs"
    include_tasks: finalise-rootfs.yaml
  tags: runtime_and_buildtime
- block:
  - name: "run user-defined scripts"
    include_tasks: buildtime-user-scripts.yaml
  tags: buildtime_only
- block:
  - name: "run system-defined scripts"
    include_tasks: runtime-system-scripts.yaml
  - name: "run user-defined scripts"
    include_tasks: runtime-user-scripts.yaml
  tags: runtime_only
