- name: "Modules | Defining modules to load"
  template:
    src: kernelmodules.j2
    dest: "/etc/modules-load.d/99-{{ item.name }}.conf"
    mode: 0644
  loop: "{{ kernel.modules.load }}"

- name: "Modules | Defining modules to blacklist"
  kernel_blacklist:
    name: "{{ item.name }}"
    state: present
  loop: "{{ kernel.modules.blacklist }}"
