- name: "Systemd | Writing user-provided systemd unit {{ item.name }}"
  template:
    src: generic-file-writer.j2
    dest: "/etc/systemd/system/{{ item.name }}"
  loop: "{{ systemd }}"
  when: run_context in item.run_contexts

- name: "Systemd | Configuring user-provided systemd unit {{ item.name }}"
  systemd:
    name: "{{ item.name }}"
    enabled: "{{ item.enabled }}"
    force: "{{ item.force }}"
  loop: "{{ systemd }}"
  when: run_context in item.run_contexts
