- name: "User Directories | Creating user-provided directory {{ item.name }}"
  file:
    path: "{{ item.name }}"
    state: directory
    mode: "{{ item.permissions }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
  with_items: "{{ directories }}"

- name: "User Files | Writing user-provided file {{ item.name }}"
  template:
    src: generic-file-writer.j2
    dest: "{{ item.name }}"
    mode: "{{ item.permissions }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
  with_items: "{{ files }}"
