src: /build
dst: /chroot
nbd_build_dir: /tmp/nbd_build_dir
img_output_dir: /config
img_name: airship-ubuntu.qcow2
qcow_capacity: 19G
qcow_compress: true
partitions:
    # Partition numbering is according to list ordering.
    # Ironic default cloud-init configdrive injection requires
    # root partition to be the first numbered partition.
    - mount: /
      mount_order: 0
      part_start: 1284MiB
      part_end: '100%'
      filesystem:
        type: ext4
        fstab:
          options: "defaults,errors=remount-ro,noatime"
          dump: 0
          fsck: 1
    - mount: none
      mount_order: 99
      part_start: 1MiB
      part_end: 5MiB
      flags:
        - bios_grub
    - mount: /boot/efi
      mount_order: 2
      part_start: 5MiB
      part_end: 516MiB
      flags:
        - esp
      filesystem:
        type: vfat
        fstab:
          options: "defaults,errors=remount-ro,noatime"
          dump: 0
          fsck: 1
    - mount: /boot
      mount_order: 1
      part_start: 516MiB
      part_end: 1284MiB
      filesystem:
        type: ext4
        fstab:
          options: "defaults,errors=remount-ro,noatime"
          dump: 0
          fsck: 2
# If any custom post-install shell scripts are needed for qcow building,
# they can be added here. This should only be used if
# osconfig_container_buildtime_scripts does not work in osconfig playbook.
qcow_container_runtime_scripts:
    - file_content: |
          #!/bin/bash
          echo "custom qcow post-install script"
