# Overrides to the multistrap playbook defaults may be defined in this file.
#
# The following are examples that show you how to override variables.
#
# Example 1: The following usage will *overwrite* the list of repos & packages
#            defined under multistrap/defaults/main.yaml with the list here:
#repos:
#  - register_repo_with_rootfs: true
#    name: Ubuntu
#    packages:
#      - package1
#      - package2
#    source: http://archive.ubuntu.com/ubuntu/
#    keyring_pkg: ubuntu-keyring
#    suite: focal
#    components: main restricted universe
#
# You would do the above in the event you had a local or other controlled mirror
# you wanted to build the image from. In this case, you will have to redefine
# everything, including the package list(s) for each mirror.
#
# Example 2: The following usage will *append* to the list of default repos
#            defined under multistrap/defaults/main.yaml with the list here:
#repos_append:
#  - register_repo_with_rootfs: true
#    name: DellUtilsRepo
#    packages:
#      - package1
#      - package2
#    source: http://dell.utils.example.com
#    keyring_pkg: ubuntu-keyring
#    suite: focal
#    components: main restricted universe
#
# You would do the above in the event you are happy with the default mirrors, but
# need to add another mirror that has additional third-party packages you require,
# such as may be needed for HW manufacturer utilities that are not published to
# the community Ubuntu mirrors.
#
# Example 3: The following usage will *append* to the list of default packages
#            installed from the default Ubuntu mirror defined in
#            multistrap/defaults/main.yaml:
#ubuntu_packages_append:
#  - package1
#  - package2
#
# You would do the above if you are happy with the default mirrors, but need to
# install some additional packages from the same mirror, for example your preferred
# text editor, troubleshooting utilities, etc.
