- name: "ensuring directory {{ root_image }}/live exists"
  file:
    path: "{{ root_image }}/live"
    state: directory
    mode: '0755'

- name: "ensure no previous squashfs file"
  file:
    path: "{{ root_image }}/live/filesystem.squashfs"
    state: absent

- name: "Building squashfs"
  shell:
    cmd: |
        mksquashfs \
            "{{ root_chroot }}" \
            "{{ root_image }}/live/filesystem.squashfs" \
            -processors {{ ansible_processor_vcpus }} \
            -e boot
