# Custom user-defined overrides to the `osconfig` playbook can be placed here.
#
# You would only use this if you needed to apply some settings uniques to this
# type of image (control-plane or data-plane). Ex: kernel boot params specific
# to workers vs non-worker nodes.
