- name: "QCOW | Installing extlinux"
  shell: |
        mkdir -p "{{ dst }}"/boot/syslinux
        extlinux --install "{{ dst }}"/boot/syslinux/ --device /dev/disk/by-partlabel/{{ ( partitions | selectattr('mount', 'equalto', '/boot') | list | first ).mount | hash('md5') }}

- name: "QCOW | Writing out syslinux config"
  copy:
    content: |
            DEFAULT linux
            SAY Booting Airship Node
            LABEL linux
            KERNEL /vmlinuz
            APPEND root=/dev/disk/by-partlabel/{{ ( partitions | selectattr('mount', 'equalto', '/') | list | first ).mount | hash('md5') }} initrd=/initrd.img
    dest: ""{{ dst }}/boot/syslinux/syslinux.cfg"


- name: "QCOW | Installing kernel and init ramdisk"
  shell: |
        rm -rf "{{ dst }}"/vmlinuz
        cp -f /mnt/image/vmlinuz "{{ dst }}"/boot/
        rm -rf /tmp/mnt/initrd.img
        cp -f /mnt/image/initrd "{{ dst }}"/boot/initrd.img
