- name: "QCOW | Mount remaining targets"
  shell: |
        set -e
        cd "{{ dst }}"
        mountpoint sys > /dev/null || mount -t sysfs /sys sys
        if [ -d /sys/firmware/efi ]; then
            mountpoint sys/firmware/efi > /dev/null || mount -o bind /sys/firmware/efi sys/firmware/efi
        fi
        mountpoint proc > /dev/null || mount -t proc /proc proc
        mountpoint dev > /dev/null || mount -o bind /dev dev
        mountpoint dev/pts > /dev/null || mount -t devpts /dev/pts dev/pts
        # temporarily override resolv.conf to working dns
        chroot "{{ dst }}" /bin/bash -c 'rm /etc/resolv.conf; echo "nameserver {{ qcow_container_runtime_scripts_dns }}" > /etc/resolv.conf'
