
- name: "QCOW | Detaching QCoW from {{ role_img_nbd_device.stdout }}"
  shell: |
        qemu-nbd -d "{{ lookup('file', '/tmp/nbd') }}"

- name: "QCOW | Compressing QCoW and writing out to {{ img_output_dir }}/{{ img_name }}"
  shell: |
        qemu-img convert -p -O qcow2 -c {{ nbd_build_dir }}/{{ img_name }} {{ img_output_dir }}/{{ img_name }}
  when: qcow_compress

- name: "QCOW | Writing QCoW to {{ img_output_dir }}/{{ img_name }}"
  shell: |
        qemu-img convert -p -O qcow2 {{ nbd_build_dir }}/{{ img_name }} {{ img_output_dir }}/{{ img_name }}
  when: not qcow_compress
