- name: "QCOW | Writing out fstab"
  include_tasks: mount-helper.yaml
  loop: "{{ partitions | sort( case_sensitive=True, attribute='mount' ) }}"
  vars:
    mount_offset: null
    state: present
    fstab: "{{ dst }}/etc/fstab"

- name: "QCOW | Setting debug password"
  shell: |
        chroot "{{ dst }}" sh -c "echo \"root:password\" | chpasswd"
